/* ================================================
   CodeGuard AI - Mock Data
   ================================================ */

const TEAM_MEMBERS = [
    { id: 1, name: 'Ana Santos', initials: 'AS', color: '#818cf8' },
    { id: 2, name: 'Carlos Oliveira', initials: 'CO', color: '#06b6d4' },
    { id: 3, name: 'Marina Costa', initials: 'MC', color: '#a78bfa' },
    { id: 4, name: 'Rafael Lima', initials: 'RL', color: '#34d399' },
    { id: 5, name: 'Juliana Ferreira', initials: 'JF', color: '#f87171' },
    { id: 6, name: 'Pedro Almeida', initials: 'PA', color: '#fbbf24' },
    { id: 7, name: 'Beatriz Souza', initials: 'BS', color: '#fb923c' },
    { id: 8, name: 'Lucas Martins', initials: 'LM', color: '#60a5fa' },
];

const MERGE_REQUESTS = [
    {
        id: 1,
        title: 'Implementar autenticação OAuth2 com refresh token',
        branch: 'feature/oauth2-auth',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[0],
        status: 'issues',
        aiScore: 62,
        createdAt: '2026-03-06T08:30:00',
        filesChanged: 12,
        additions: 342,
        deletions: 87,
        comments: 5,
        description: 'Implementação completa do fluxo OAuth2 com suporte a refresh token e renovação automática de sessão.',
        files: [
            { name: 'src/auth/OAuthService.js', additions: 145, deletions: 12 },
            { name: 'src/auth/TokenManager.js', additions: 89, deletions: 34 },
            { name: 'src/middleware/authMiddleware.js', additions: 56, deletions: 23 },
            { name: 'src/config/oauth.config.js', additions: 28, deletions: 8 },
            { name: 'tests/auth/oauth.test.js', additions: 24, deletions: 10 },
        ],
        diff: [
            {
                file: 'src/auth/OAuthService.js',
                lines: [
                    { type: 'context', num: 1, content: 'import { HttpClient } from \'../utils/http\';' },
                    { type: 'context', num: 2, content: 'import { Logger } from \'../utils/logger\';' },
                    { type: 'added', num: 3, content: 'import { TokenManager } from \'./TokenManager\';' },
                    { type: 'added', num: 4, content: 'import { OAuthConfig } from \'../config/oauth.config\';' },
                    { type: 'context', num: 5, content: '' },
                    { type: 'context', num: 6, content: 'export class OAuthService {' },
                    { type: 'removed', num: 7, content: '  constructor(config) {' },
                    { type: 'added', num: 7, content: '  constructor() {' },
                    { type: 'added', num: 8, content: '    const config = OAuthConfig.getInstance();' },
                    { type: 'context', num: 9, content: '    this.clientId = config.clientId;' },
                    { type: 'context', num: 10, content: '    this.clientSecret = config.clientSecret;' },
                    { type: 'added', num: 11, content: '    this.tokenManager = new TokenManager();' },
                    { type: 'context', num: 12, content: '  }' },
                    { type: 'context', num: 13, content: '' },
                    { type: 'added', num: 14, content: '  async authenticate(code) {' },
                    { type: 'added', num: 15, content: '    const tokens = await this.exchangeCode(code);' },
                    { type: 'added', num: 16, content: '    this.tokenManager.store(tokens);' },
                    { type: 'added', num: 17, content: '    return tokens;' },
                    { type: 'added', num: 18, content: '  }' },
                    { type: 'context', num: 19, content: '' },
                    { type: 'added', num: 20, content: '  async refreshToken() {' },
                    { type: 'added', num: 21, content: '    const token = this.tokenManager.getRefreshToken();' },
                    { type: 'added', num: 22, content: '    // TODO: add error handling' },
                    { type: 'added', num: 23, content: '    const response = await HttpClient.post(\'/oauth/token\', {' },
                    { type: 'added', num: 24, content: '      grant_type: \'refresh_token\',' },
                    { type: 'added', num: 25, content: '      refresh_token: token,' },
                    { type: 'added', num: 26, content: '      client_secret: this.clientSecret' },
                    { type: 'added', num: 27, content: '    });' },
                    { type: 'added', num: 28, content: '    return response.data;' },
                    { type: 'added', num: 29, content: '  }' },
                    { type: 'context', num: 30, content: '}' },
                ],
                annotations: [
                    { afterLine: 22, type: 'danger', text: '⚠️ Crítico: Falta tratamento de erro no refreshToken(). Se o refresh falhar, o usuário ficará sem sessão. Adicione try/catch e implemente fallback para re-autenticação.' },
                    { afterLine: 26, type: 'warning', text: '🔐 Segurança: O client_secret não deveria ser enviado diretamente no body do request. Use um header Authorization com Basic auth conforme RFC 6749 §2.3.1.' },
                    { afterLine: 11, type: 'info', text: '💡 Sugestão: Considere usar injeção de dependência para TokenManager ao invés de instanciar diretamente no construtor. Isso facilitará os testes unitários.' },
                ]
            },
            {
                file: 'src/auth/TokenManager.js',
                lines: [
                    { type: 'context', num: 1, content: 'export class TokenManager {' },
                    { type: 'added', num: 2, content: '  constructor() {' },
                    { type: 'added', num: 3, content: '    this.accessToken = null;' },
                    { type: 'added', num: 4, content: '    this.refreshToken = null;' },
                    { type: 'added', num: 5, content: '    this.expiresAt = null;' },
                    { type: 'added', num: 6, content: '  }' },
                    { type: 'context', num: 7, content: '' },
                    { type: 'added', num: 8, content: '  store(tokens) {' },
                    { type: 'added', num: 9, content: '    this.accessToken = tokens.access_token;' },
                    { type: 'added', num: 10, content: '    this.refreshToken = tokens.refresh_token;' },
                    { type: 'added', num: 11, content: '    localStorage.setItem(\'tokens\', JSON.stringify(tokens));' },
                    { type: 'added', num: 12, content: '  }' },
                    { type: 'context', num: 13, content: '' },
                    { type: 'added', num: 14, content: '  getAccessToken() {' },
                    { type: 'added', num: 15, content: '    return this.accessToken;' },
                    { type: 'added', num: 16, content: '  }' },
                    { type: 'context', num: 17, content: '}' },
                ],
                annotations: [
                    { afterLine: 11, type: 'danger', text: '🔴 Vulnerabilidade: Armazenar tokens sensíveis em localStorage é inseguro — vulnerável a ataques XSS. Use httpOnly cookies ou sessionStorage com criptografia.' },
                ]
            }
        ],
        issues: [
            { severity: 'critical', title: 'Tokens armazenados em localStorage', description: 'Armazenar access_token e refresh_token em localStorage expõe os tokens a ataques XSS. Tokens sensíveis devem ser armazenados em httpOnly cookies.', file: 'src/auth/TokenManager.js:11', suggestion: 'Migrar o armazenamento de tokens para httpOnly cookies com flag Secure e SameSite=Strict.' },
            { severity: 'critical', title: 'Falta tratamento de erro no refresh', description: 'O método refreshToken() não possui tratamento de erros. Se o refresh token expirar ou for inválido, a aplicação pode quebrar silenciosamente.', file: 'src/auth/OAuthService.js:20-29', suggestion: 'Adicionar try/catch com fallback para redirecionamento ao login e invalidação da sessão corrente.' },
            { severity: 'warning', title: 'Client secret no body do request', description: 'O client_secret está sendo enviado no body da requisição POST. A RFC 6749 recomenda usar HTTP Basic Authentication para credenciais do cliente.', file: 'src/auth/OAuthService.js:26', suggestion: 'Enviar as credenciais no header Authorization usando Base64(client_id:client_secret).' },
            { severity: 'info', title: 'Acoplamento no construtor', description: 'TokenManager é instanciado diretamente no construtor de OAuthService, dificultando testes unitários com mocks.', file: 'src/auth/OAuthService.js:11', suggestion: 'Usar injeção de dependência: receber TokenManager como parâmetro do construtor.' },
            { severity: 'suggestion', title: 'Ausência de validação de expiração', description: 'A classe TokenManager armazena expiresAt mas nunca valida se o token atual está expirado antes de retorná-lo.', file: 'src/auth/TokenManager.js:14-16', suggestion: 'Adicionar método isExpired() e verificar antes de retornar o token no getAccessToken().' },
        ],
        analysisCategories: {
            security: 42,
            performance: 78,
            readability: 71,
            businessRules: 65,
        },
        rules: [
            { name: 'Sem credenciais hardcoded', status: 'pass', desc: 'Verificação de senhas, tokens ou chaves no código.' },
            { name: 'Tratamento de erros em chamadas async', status: 'fail', desc: 'Todas as chamadas assíncronas devem ter try/catch.' },
            { name: 'Padrão de nomenclatura de classes', status: 'pass', desc: 'Classes devem usar PascalCase.' },
            { name: 'Armazenamento seguro de dados sensíveis', status: 'fail', desc: 'Dados sensíveis não devem usar localStorage.' },
            { name: 'Documentação de métodos públicos', status: 'warn', desc: 'Métodos públicos devem ter JSDoc comments.' },
            { name: 'Testes unitários', status: 'pass', desc: 'Cobertura mínima de testes unitários.' },
            { name: 'Injeção de dependência', status: 'warn', desc: 'Preferir DI ao invés de instanciação direta.' },
            { name: 'Importações não utilizadas', status: 'pass', desc: 'Sem imports desnecessários no código.' },
        ]
    },
    {
        id: 2,
        title: 'Refatorar módulo de notificações push',
        branch: 'refactor/push-notifications',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[2],
        status: 'approved',
        aiScore: 91,
        createdAt: '2026-03-05T14:20:00',
        filesChanged: 6,
        additions: 178,
        deletions: 234,
        comments: 2,
        description: 'Refatoração do módulo de push notifications para usar o padrão Observer e melhorar testabilidade.',
        files: [
            { name: 'src/notifications/PushService.js', additions: 82, deletions: 120 },
            { name: 'src/notifications/NotificationObserver.js', additions: 45, deletions: 0 },
            { name: 'src/notifications/channels/EmailChannel.js', additions: 23, deletions: 56 },
            { name: 'tests/notifications/push.test.js', additions: 28, deletions: 58 },
        ],
        diff: [
            {
                file: 'src/notifications/PushService.js',
                lines: [
                    { type: 'context', num: 1, content: 'import { EventEmitter } from \'events\';' },
                    { type: 'added', num: 2, content: 'import { NotificationObserver } from \'./NotificationObserver\';' },
                    { type: 'context', num: 3, content: '' },
                    { type: 'removed', num: 4, content: 'export class PushService extends EventEmitter {' },
                    { type: 'added', num: 4, content: 'export class PushService {' },
                    { type: 'added', num: 5, content: '  #observers = new Set();' },
                    { type: 'context', num: 6, content: '' },
                    { type: 'added', num: 7, content: '  subscribe(observer) {' },
                    { type: 'added', num: 8, content: '    if (observer instanceof NotificationObserver) {' },
                    { type: 'added', num: 9, content: '      this.#observers.add(observer);' },
                    { type: 'added', num: 10, content: '    }' },
                    { type: 'added', num: 11, content: '  }' },
                    { type: 'context', num: 12, content: '' },
                    { type: 'added', num: 13, content: '  async notify(event) {' },
                    { type: 'added', num: 14, content: '    for (const observer of this.#observers) {' },
                    { type: 'added', num: 15, content: '      await observer.handle(event);' },
                    { type: 'added', num: 16, content: '    }' },
                    { type: 'added', num: 17, content: '  }' },
                    { type: 'context', num: 18, content: '}' },
                ],
                annotations: [
                    { afterLine: 15, type: 'info', text: '💡 Boa prática: Considere usar Promise.allSettled() ao invés de await sequencial para notificar observers em paralelo e evitar que uma falha bloqueie as demais.' },
                ]
            }
        ],
        issues: [
            { severity: 'suggestion', title: 'Notificação sequencial de observers', description: 'Os observers são notificados sequencialmente com await. Isso pode causar lentidão se houver muitos observers.', file: 'src/notifications/PushService.js:14-16', suggestion: 'Usar Promise.allSettled() para execução paralela com resiliência a falhas individuais.' },
        ],
        analysisCategories: { security: 95, performance: 82, readability: 94, businessRules: 92 },
        rules: [
            { name: 'Padrão de nomenclatura de classes', status: 'pass', desc: 'Classes usam PascalCase.' },
            { name: 'Sem dependências circulares', status: 'pass', desc: 'Sem imports circulares detectados.' },
            { name: 'Tratamento de erros em chamadas async', status: 'pass', desc: 'Chamadas assíncronas tratadas corretamente.' },
            { name: 'Documentação de métodos públicos', status: 'pass', desc: 'Todos os métodos públicos documentados.' },
            { name: 'Design Pattern adequado', status: 'pass', desc: 'Pattern Observer implementado corretamente.' },
            { name: 'Testes unitários', status: 'pass', desc: 'Cobertura de testes adequada.' },
        ]
    },
    {
        id: 3,
        title: 'Adicionar cache Redis no serviço de produtos',
        branch: 'feature/redis-cache-products',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[1],
        status: 'pending',
        aiScore: 78,
        createdAt: '2026-03-06T10:15:00',
        filesChanged: 8,
        additions: 256,
        deletions: 45,
        comments: 0,
        description: 'Cache em Redis para queries pesadas do catálogo de produtos, com invalidação por TTL e eventos.',
        files: [
            { name: 'src/cache/RedisClient.js', additions: 67, deletions: 0 },
            { name: 'src/products/ProductService.js', additions: 89, deletions: 23 },
            { name: 'src/cache/CacheInvalidator.js', additions: 45, deletions: 12 },
            { name: 'src/config/redis.config.js', additions: 22, deletions: 0 },
            { name: 'tests/cache/redis.test.js', additions: 33, deletions: 10 },
        ],
        diff: [
            {
                file: 'src/products/ProductService.js',
                lines: [
                    { type: 'context', num: 1, content: 'import { ProductRepository } from \'./ProductRepository\';' },
                    { type: 'added', num: 2, content: 'import { RedisClient } from \'../cache/RedisClient\';' },
                    { type: 'context', num: 3, content: '' },
                    { type: 'context', num: 4, content: 'export class ProductService {' },
                    { type: 'added', num: 5, content: '  #cache = new RedisClient();' },
                    { type: 'added', num: 6, content: '  #CACHE_TTL = 3600;' },
                    { type: 'context', num: 7, content: '' },
                    { type: 'removed', num: 8, content: '  async getProducts(filters) {' },
                    { type: 'added', num: 8, content: '  async getProducts(filters = {}) {' },
                    { type: 'added', num: 9, content: '    const cacheKey = `products:${JSON.stringify(filters)}`;' },
                    { type: 'added', num: 10, content: '    const cached = await this.#cache.get(cacheKey);' },
                    { type: 'added', num: 11, content: '    if (cached) return JSON.parse(cached);' },
                    { type: 'context', num: 12, content: '' },
                    { type: 'context', num: 13, content: '    const products = await this.repository.findAll(filters);' },
                    { type: 'added', num: 14, content: '    await this.#cache.set(cacheKey, JSON.stringify(products), this.#CACHE_TTL);' },
                    { type: 'context', num: 15, content: '    return products;' },
                    { type: 'context', num: 16, content: '  }' },
                    { type: 'context', num: 17, content: '}' },
                ],
                annotations: [
                    { afterLine: 9, type: 'warning', text: '⚠️ A chave de cache usa JSON.stringify(filters) que pode gerar chaves inconsistentes dependendo da ordem das propriedades do objeto. Use uma função de hash ou ordene as chaves antes.' },
                    { afterLine: 6, type: 'info', text: '💡 O TTL de 3600s (1h) pode ser muito longo para dados de produtos que mudam frequentemente. Considere configurar via variável de ambiente.' },
                ]
            }
        ],
        issues: [
            { severity: 'warning', title: 'Chaves de cache inconsistentes', description: 'JSON.stringify não garante ordem das propriedades, gerando chaves diferentes para mesmos filtros.', file: 'src/products/ProductService.js:9', suggestion: 'Usar uma função de serialização determinística, como sorted-json-stringify.' },
            { severity: 'info', title: 'TTL hardcoded', description: 'O TTL de cache está hardcoded como 3600 segundos.', file: 'src/products/ProductService.js:6', suggestion: 'Mover para variável de ambiente ou arquivo de configuração.' },
            { severity: 'suggestion', title: 'Sem circuit breaker para Redis', description: 'Se o Redis ficar indisponível, as queries vão falhar em vez de fazer fallback ao banco.', file: 'src/cache/RedisClient.js', suggestion: 'Implementar pattern Circuit Breaker para fallback graceful ao banco de dados.' },
        ],
        analysisCategories: { security: 88, performance: 72, readability: 85, businessRules: 78 },
        rules: [
            { name: 'Padrão de nomenclatura de classes', status: 'pass', desc: 'Classes usam PascalCase.' },
            { name: 'Configuração externalizada', status: 'warn', desc: 'Algumas configs estão hardcoded.' },
            { name: 'Tratamento de erros em chamadas async', status: 'pass', desc: 'Chamadas assíncronas tratadas.' },
            { name: 'Resiliência de integrações externas', status: 'fail', desc: 'Sem fallback para indisponibilidade do Redis.' },
            { name: 'Testes unitários', status: 'pass', desc: 'Testes presentes para os novos módulos.' },
        ]
    },
    {
        id: 4,
        title: 'Corrigir race condition no processamento de pagamentos',
        branch: 'bugfix/payment-race-condition',
        targetBranch: 'main',
        author: TEAM_MEMBERS[3],
        status: 'issues',
        aiScore: 55,
        createdAt: '2026-03-05T16:45:00',
        filesChanged: 4,
        additions: 67,
        deletions: 23,
        comments: 8,
        description: 'Correção de race condition que permitia processamento duplicado de pagamentos em requisições concorrentes.',
        files: [
            { name: 'src/payments/PaymentProcessor.js', additions: 34, deletions: 12 },
            { name: 'src/payments/LockManager.js', additions: 18, deletions: 0 },
            { name: 'src/payments/PaymentValidator.js', additions: 9, deletions: 7 },
            { name: 'tests/payments/concurrent.test.js', additions: 6, deletions: 4 },
        ],
        diff: [
            {
                file: 'src/payments/PaymentProcessor.js',
                lines: [
                    { type: 'context', num: 1, content: 'import { PaymentGateway } from \'./PaymentGateway\';' },
                    { type: 'added', num: 2, content: 'import { LockManager } from \'./LockManager\';' },
                    { type: 'context', num: 3, content: '' },
                    { type: 'context', num: 4, content: 'export class PaymentProcessor {' },
                    { type: 'added', num: 5, content: '  #lockManager = new LockManager();' },
                    { type: 'context', num: 6, content: '' },
                    { type: 'context', num: 7, content: '  async processPayment(order) {' },
                    { type: 'added', num: 8, content: '    const lockKey = `payment:${order.id}`;' },
                    { type: 'added', num: 9, content: '    const lock = await this.#lockManager.acquire(lockKey);' },
                    { type: 'context', num: 10, content: '' },
                    { type: 'added', num: 11, content: '    const result = await this.gateway.charge(order);' },
                    { type: 'added', num: 12, content: '    await this.#lockManager.release(lockKey);' },
                    { type: 'added', num: 13, content: '    return result;' },
                    { type: 'context', num: 14, content: '  }' },
                    { type: 'context', num: 15, content: '}' },
                ],
                annotations: [
                    { afterLine: 12, type: 'danger', text: '🔴 Crítico: Se gateway.charge() lançar uma exceção, o lock nunca será liberado (deadlock). Use try/finally para garantir a liberação do lock.' },
                    { afterLine: 9, type: 'warning', text: '⚠️ Não há timeout no acquire do lock. Se o lock nunca for liberado, a thread ficará bloqueada indefinidamente.' },
                ]
            }
        ],
        issues: [
            { severity: 'critical', title: 'Deadlock potencial no processamento', description: 'O lock não é liberado em caso de exceção no gateway.charge(), causando deadlock permanente.', file: 'src/payments/PaymentProcessor.js:9-12', suggestion: 'Usar bloco try/finally para garantir liberação do lock independente de exceções.' },
            { severity: 'critical', title: 'Sem timeout no acquire de lock', description: 'O método acquire() não tem timeout, podendo bloquear a thread indefinidamente.', file: 'src/payments/PaymentProcessor.js:9', suggestion: 'Adicionar timeout com auto-release e tratamento de timeout exceeded.' },
            { severity: 'warning', title: 'Testes de concorrência insuficientes', description: 'Os testes de concorrência foram reduzidos, não cobrindo cenários de falha com lock.', file: 'tests/payments/concurrent.test.js', suggestion: 'Adicionar testes para cenários: timeout de lock, exceção durante cobrança, lock expirado.' },
        ],
        analysisCategories: { security: 68, performance: 45, readability: 76, businessRules: 52 },
        rules: [
            { name: 'Tratamento de erros em chamadas async', status: 'fail', desc: 'Lock não é liberado em caso de exceção.' },
            { name: 'Resiliência em operações financeiras', status: 'fail', desc: 'Falta timeout e retry no processamento.' },
            { name: 'Testes de cenários de falha', status: 'fail', desc: 'Faltam testes de edge cases.' },
            { name: 'Padrão de nomenclatura de classes', status: 'pass', desc: 'Classes usam PascalCase.' },
            { name: 'Idempotência em operações críticas', status: 'warn', desc: 'Processamento não é idempotente.' },
        ]
    },
    {
        id: 5,
        title: 'Implementar paginação no endpoint de relatórios',
        branch: 'feature/reports-pagination',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[4],
        status: 'approved',
        aiScore: 88,
        createdAt: '2026-03-04T09:30:00',
        filesChanged: 5,
        additions: 134,
        deletions: 42,
        comments: 1,
        description: 'Paginação cursor-based para o endpoint de relatórios, com suporte a ordenação e filtros.',
        files: [
            { name: 'src/reports/ReportController.js', additions: 45, deletions: 18 },
            { name: 'src/reports/ReportRepository.js', additions: 56, deletions: 12 },
            { name: 'src/utils/Paginator.js', additions: 33, deletions: 12 },
        ],
        diff: [
            {
                file: 'src/reports/ReportController.js',
                lines: [
                    { type: 'context', num: 1, content: 'export class ReportController {' },
                    { type: 'removed', num: 2, content: '  async list(req, res) {' },
                    { type: 'removed', num: 3, content: '    const reports = await this.service.getAll();' },
                    { type: 'added', num: 2, content: '  async list(req, res) {' },
                    { type: 'added', num: 3, content: '    const { cursor, limit = 20, sort } = req.query;' },
                    { type: 'added', num: 4, content: '    const result = await this.service.getPaginated({' },
                    { type: 'added', num: 5, content: '      cursor, limit: Math.min(limit, 100), sort' },
                    { type: 'added', num: 6, content: '    });' },
                    { type: 'context', num: 7, content: '' },
                    { type: 'added', num: 8, content: '    res.json({' },
                    { type: 'added', num: 9, content: '      data: result.items,' },
                    { type: 'added', num: 10, content: '      pagination: {' },
                    { type: 'added', num: 11, content: '        nextCursor: result.nextCursor,' },
                    { type: 'added', num: 12, content: '        hasMore: result.hasMore,' },
                    { type: 'added', num: 13, content: '        total: result.total' },
                    { type: 'added', num: 14, content: '      }' },
                    { type: 'added', num: 15, content: '    });' },
                    { type: 'context', num: 16, content: '  }' },
                    { type: 'context', num: 17, content: '}' },
                ],
                annotations: [
                    { afterLine: 5, type: 'info', text: '✅ Boa prática: Limite máximo de 100 itens por página evita queries pesadas. Excelente uso de Math.min().' },
                ]
            }
        ],
        issues: [
            { severity: 'suggestion', title: 'Sanitização do parâmetro sort', description: 'O parâmetro sort é passado diretamente do query string sem validação.', file: 'src/reports/ReportController.js:3', suggestion: 'Criar whitelist de campos permitidos para ordenação.' },
        ],
        analysisCategories: { security: 82, performance: 91, readability: 93, businessRules: 88 },
        rules: [
            { name: 'Paginação em listagens', status: 'pass', desc: 'Endpoint usa paginação cursor-based.' },
            { name: 'Limite de resultados por página', status: 'pass', desc: 'Limite máximo de 100 itens.' },
            { name: 'Validação de input do usuário', status: 'warn', desc: 'Parâmetro sort sem whitelist.' },
            { name: 'Padrão de resposta da API', status: 'pass', desc: 'Resposta segue formato padronizado.' },
            { name: 'Testes unitários', status: 'pass', desc: 'Testes de paginação presentes.' },
        ]
    },
    {
        id: 6,
        title: 'Migrar logging para Winston com structured logs',
        branch: 'chore/winston-structured-logging',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[5],
        status: 'analyzing',
        aiScore: null,
        createdAt: '2026-03-06T11:00:00',
        filesChanged: 14,
        additions: 312,
        deletions: 189,
        comments: 0,
        description: 'Migração do sistema de logging para Winston com logs estruturados em JSON para melhor observabilidade.',
        files: [
            { name: 'src/logging/WinstonLogger.js', additions: 78, deletions: 0 },
            { name: 'src/logging/transports/CloudTransport.js', additions: 45, deletions: 0 },
        ],
        diff: [],
        issues: [],
        analysisCategories: { security: 0, performance: 0, readability: 0, businessRules: 0 },
        rules: []
    },
    {
        id: 7,
        title: 'Otimizar queries N+1 no módulo de usuários',
        branch: 'perf/fix-n-plus-1-users',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[6],
        status: 'merged',
        aiScore: 95,
        createdAt: '2026-03-03T15:00:00',
        filesChanged: 3,
        additions: 45,
        deletions: 67,
        comments: 3,
        description: 'Correção de queries N+1 no módulo de usuários usando eager loading e batch queries.',
        files: [
            { name: 'src/users/UserRepository.js', additions: 28, deletions: 45 },
            { name: 'src/users/UserService.js', additions: 12, deletions: 18 },
            { name: 'tests/users/performance.test.js', additions: 5, deletions: 4 },
        ],
        diff: [],
        issues: [],
        analysisCategories: { security: 96, performance: 97, readability: 92, businessRules: 95 },
        rules: [
            { name: 'Performance de queries', status: 'pass', desc: 'Sem queries N+1 detectadas.' },
            { name: 'Eager loading', status: 'pass', desc: 'Relações carregadas de forma otimizada.' },
            { name: 'Testes de performance', status: 'pass', desc: 'Testes de desempenho incluídos.' },
        ]
    },
    {
        id: 8,
        title: 'Adicionar rate limiting na API pública',
        branch: 'feature/api-rate-limiting',
        targetBranch: 'develop',
        author: TEAM_MEMBERS[7],
        status: 'pending',
        aiScore: 83,
        createdAt: '2026-03-06T09:00:00',
        filesChanged: 7,
        additions: 198,
        deletions: 12,
        comments: 2,
        description: 'Rate limiting com sliding window para endpoints públicos da API, com headers padrão X-RateLimit.',
        files: [
            { name: 'src/middleware/rateLimiter.js', additions: 78, deletions: 0 },
            { name: 'src/config/rateLimit.config.js', additions: 34, deletions: 0 },
            { name: 'src/middleware/index.js', additions: 12, deletions: 4 },
        ],
        diff: [],
        issues: [
            { severity: 'warning', title: 'Rate limit por IP pode ser burlado', description: 'Rate limiting baseado apenas em IP pode ser contornado com proxies ou VPNs.', file: 'src/middleware/rateLimiter.js', suggestion: 'Combinar IP com API key ou fingerprint do cliente para identificação mais robusta.' },
            { severity: 'info', title: 'Considerar distributed rate limiting', description: 'Em ambiente com múltiplas instâncias, rate limiting local não é efetivo.', file: 'src/middleware/rateLimiter.js', suggestion: 'Usar Redis como backend compartilhado para contadores de rate limit.' },
        ],
        analysisCategories: { security: 80, performance: 85, readability: 88, businessRules: 79 },
        rules: [
            { name: 'Rate limiting em endpoints públicos', status: 'pass', desc: 'Rate limiting implementado.' },
            { name: 'Headers de rate limit padrão', status: 'pass', desc: 'Headers X-RateLimit presentes.' },
            { name: 'Distribuição em cluster', status: 'warn', desc: 'Rate limit não é distribuído.' },
        ]
    },
];

const CHART_DATA = [
    { label: 'Seg', value: 12 },
    { label: 'Ter', value: 18 },
    { label: 'Qua', value: 8 },
    { label: 'Qui', value: 24 },
    { label: 'Sex', value: 15 },
    { label: 'Sáb', value: 5 },
    { label: 'Dom', value: 3 },
];

const RECENT_ACTIVITY = [
    { text: 'MR #7 "Otimizar queries N+1" foi merged', type: 'merged', time: '2h atrás' },
    { text: 'MR #2 "Refatorar notificações" aprovado pela IA', type: 'review', time: '4h atrás' },
    { text: 'MR #4 "Race condition pagamentos" rejeitado', type: 'rejected', time: '5h atrás' },
    { text: 'MR #6 "Winston logging" aguardando análise', type: 'pending', time: '17min atrás' },
    { text: 'MR #1 "OAuth2 auth" identificou 5 issues', type: 'rejected', time: '3h atrás' },
    { text: 'MR #5 "Paginação relatórios" aprovado', type: 'review', time: '1d atrás' },
];

const CONFIGURABLE_RULES = [
    { id: 1, name: 'Tratamento de Erros Async', desc: 'Todas as chamadas assíncronas (await) devem estar dentro de blocos try/catch com tratamento adequado.', severity: 'critical', active: true },
    { id: 2, name: 'Armazenamento Seguro', desc: 'Dados sensíveis (tokens, senhas, chaves) não devem ser armazenados em localStorage ou sessionStorage.', severity: 'critical', active: true },
    { id: 3, name: 'Sem Credenciais Hardcoded', desc: 'Credenciais, API keys e secrets não devem estar no código-fonte. Use variáveis de ambiente.', severity: 'critical', active: true },
    { id: 4, name: 'Nomenclatura de Classes', desc: 'Classes devem usar PascalCase. Métodos e variáveis devem usar camelCase.', severity: 'warning', active: true },
    { id: 5, name: 'Documentação JSDoc', desc: 'Métodos públicos devem ter documentação JSDoc com @param e @returns.', severity: 'info', active: true },
    { id: 6, name: 'Injeção de Dependência', desc: 'Preferir injeção de dependência ao invés de instanciação direta em construtores.', severity: 'info', active: false },
    { id: 7, name: 'Paginação em Listagens', desc: 'Endpoints de listagem devem implementar paginação (cursor ou offset-based).', severity: 'warning', active: true },
    { id: 8, name: 'Rate Limiting', desc: 'Endpoints públicos devem implementar rate limiting por IP e/ou API key.', severity: 'warning', active: true },
    { id: 9, name: 'Resiliência de Integrações', desc: 'Integrações externas devem implementar circuit breaker, timeout e retry.', severity: 'critical', active: true },
    { id: 10, name: 'Testes Unitários Mínimos', desc: 'Novas funcionalidades devem ter pelo menos 80% de cobertura de testes unitários.', severity: 'warning', active: true },
    { id: 11, name: 'Idempotência em Operações Críticas', desc: 'Operações financeiras e de estado devem ser idempotentes com chaves de idempotência.', severity: 'critical', active: true },
    { id: 12, name: 'Limite de Complexidade Ciclomática', desc: 'Funções não devem exceder complexidade ciclomática de 10.', severity: 'info', active: false },
];
